config/routes.rb
Rails.application.routes.draw do
  resources :events do
    member do
      get 'rsvp'
      get 'cancel_rsvp'
      get 'my_event', to: 'events#my_event'
    end
  end  # post '/events', to: 'events#create'
  resources :users #only: [:index, :create]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  get '/logout', to: 'sessions#destroy'
  root to: "static#home"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :event_name, :event_date, :event_location, presence: true
  # validates :event_name, uniqueness: true
  validates :event_name, :event_location, length: { minimum: 4 }

  belongs_to :hoster, class_name: 'User'
  has_many :event_users, foreign_key: :attended_event_id
  has_many :attendees, through: :event_users, foreign_key: :attendee_id

  scope :past, -> { where('event_date < ?', Date.today).order(event_date: :desc) }
  scope :future, -> { where('event_date > ?', Date.today).order(:event_date) }
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :login_id, presence: true
  validates :name, :login_id, uniqueness: true
  validates :name, :login_id, length: { minimum: 4 }
  validates :name, format: { with: /\A[a-zA-Z]+\z/, message: 'Please enter only letters' }
  validates :login_id, format: { with: /\A[0-9]+\z/, message: 'Please enter only numbers' }

  has_many :hoster_events, foreign_key: :hoster_id, class_name: 'Event'
  has_many :event_users, foreign_key: :attendee_id
  has_many :attended_events, through: :event_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  # helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, only: %i[show index]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.hoster_events.build(event_params)
    if @event.save
      redirect_to @event, notice: 'Event has been created'
    else
      render 'new', notice: 'Try again'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: 'Your event was updated'
    else
      render :edit
    end
  end

  def rsvp
    @event = Event.find(params[:id])
    if @event.attendees.include?(current_user)
      redirect_to @event, notice: 'You are already enrolled on this event.'
    else
      @event.attendees << current_user
      redirect_to @event, notice: 'You are now in line to attend this event.'
    end
  end

  def cancel_rsvp
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    redirect_to @event, notice: 'You are no longer on this event.'
  end

  def my_event
    @event = current_user.hoster_events.all
  end

  def destroy
    @event = Event.find_by(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :event_location, :event_date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(name: params[:name])
    if user
      log_in(user)
      redirect_to events_path, notice: 'logged in successfully!'
    else
      render 'new', notice: 'User not found'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'You are logged out!'
  end

  private

  def sign_param
    params.require(:session).permit(:name)
  end

  def search
    params[:id]
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true ...
class StaticController < ApplicationController
  def home
    @events = Event.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[show destroy index]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    # session.delete(:user_id)
    redirect_to users_path, notice: 'User deleted'
    # session.clear
    reset_session
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_user
  #   @user = User.find(params[:id])
  # end

  def correct_user?
    user = User.find(params[:id])
    user == current_user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :login_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def require_login
    redirect_to login_path, notice: 'not signed in, Sign in' if current_user.nil?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :event_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :event_location, class: 'form-control' %>
  </div>
  

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :event_date, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Event', class: 'btn btn-lg text-light bg-dark a-l' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<%if current_user%>
<h1>Upcoming Events</h1>

<div class='event-card'>
  <% Event.future.each do |event| %>
  <div class="event-head">
    <h1>Event: <%= event.event_name%></h1>
  </div>
  <div class="event-body">
    <p>Happening at: <%= event.event_location%></p>
    <p>Date: <%= event.event_date%></p>
    <small>Created at <%= event.created_at%> </small>
    <%= link_to 'About', event_path(event) %>
  </div>
  <% end %>
</div>


<hr style='background: white; height: 30px'>

<h1>Past Events</h1>
<div class='event-card'>
  <% Event.past.each do |event| %>
  <div class="event-head">
    <h1>Event: <%= event.event_name%></h1>
  </div>
  <div class="event-body">
    <p>Happening at: <%= event.event_location%></p>
    <p>Date: <%= event.event_date%></p>
    <small>Created at <%= event.created_at%> </small>
    <%= link_to 'About', event_path(event) %>
  </div>
  <% end %>
</div>

<%= link_to 'Add Event', new_event_path %>
<%else%>
  redirect_to '/login'
<%end%>

app/views/events/my_event.html.erb
<% @event.each do |event| %>
<div class="card border-success m-4" style="max-width: 18rem;">
  <div class="card-header bg-primary border-success">Created by <%= link_to event.hoster.name, user_path(event.hoster) %></div>
  <div class="card-body text-success">
    <h5 class="card-title bg-primary text-dark p-2 bg-light text-dark">Event: <%= event.event_name%></h5>
    <p class="card-text">Location: <%= event.event_location%>.</p>
    <p class="card-text">Date: <%= event.event_date%>.</p>
  </div>
  <div class="card-footer bg-primary border-success"><%= link_to 'Back to event', events_path, class: 'p-2 bg-light text-dark' %>
</div>
</div><% end %>

app/views/events/new.html.erb
<h1>Create new Event here</h1>

<%= render 'form' %>

<%= link_to 'Events', events_path, class: 'btn btn-light text-dark a-l' %>

app/views/events/show.html.erb
<h1><%= current_user.name%>  Event here</h1>
<% if @event.event_date < Time.now %>
  <p>Sorry, you cannot attend this event again because it has already <b>PAST</b></p>
<% end %>

<% if current_user == @event.hoster %>
  <%= link_to 'Edit', edit_event_path, class: "btn btn-outline-secondary" %>
  <%= link_to 'Delete', event_path(@event), method: :delete, class: "btn btn-outline-secondary m-3", data: { confirm: "Delete this event?"} %>
<% elsif @event.attendees.include?(current_user) %>
  <%= link_to 'Cancel RSVP', cancel_rsvp_event_path, class: "btn btn-outline-secondary m-3" %>
<% else %>
  <%= link_to 'RSVP', rsvp_event_path, class: "btn btn-primary m-3" unless @event.event_date < Time.now %>
<% end %>

<div class="card border-success m-4" style="max-width: 18rem;">
  <div class="card-header bg-primary border-success">Created by <%= link_to @event.hoster.name, user_path(@event.hoster) %></div>
  <div class="card-body text-success">
    <h5 class="card-title bg-primary text-dark p-2 bg-light text-dark">Event: <%= @event.event_name%></h5>
    <p class="card-text">Location: <%= @event.event_location%>.</p>
    <p class="card-text">Date: <%= @event.event_date%>.</p>
  </div>
  <div class="card-footer bg-primary border-success"><%= link_to 'Back to event', events_path, class: 'p-2 bg-light text-dark' %>
</div>
</div>

<h1>Attendees list</h1>
<% if @event.attendees.empty? %>
  <h6>There are no attendees yet</h6>
<% else %>
  <% @event.attendees.each do |attendees| %>
    <h5 class='bg-primary'><%= attendees.name%></h5>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <%# <nav class='navbar navbar-light navbar-expand-lg bg-primary'> %>
    <ul class='nav nav-tab bg-mute p-2 my-4 border navbar-expand-sm'>
    <%if current_user%>
    <li class='nav-item'>
    <%= link_to 'Sign out', logout_path, method: :get, class: 'text-primary nav-link text-sm-center' %>
    </li>

    <li class='nav-item'>
    <%= link_to 'All Events', events_url, method: :get, class: 'text-primary nav-link text-sm-center' %>
    </li>
    <li class='nav-item'>
    <%= link_to 'Add Events', new_event_path, method: :get, class: 'text-primary nav-link text-sm-center' %>
    </li>

    <li class='nav-item'>
    <%= link_to 'See my Events', my_event_event_path(current_user), class: 'text-primary nav-link text-sm-center' %>
    </li>
    <h3>Signed in as <%= current_user.name%></h3>
    <%else%>
    <li class='nav-item'>
    <%= link_to 'Sign up', new_user_path, class: 'text-primary nav-link text-sm-center' %>
    </li>
    <li class='nav-item'>
    <%= link_to 'Home', root_path, class: 'text-primary nav-link text-sm-center' %>
    </li>
    <li class='nav-item'>
    <%= link_to 'Sign in', login_path, class: 'text-primary nav-link text-sm-center' %>
    </li>
    <%end%> 
    </ul>

    <% if notice%>
      <p class='notice'><%= notice%></p>
    <% end%>
    
    <% if flash%>
      <% flash.each do |f, m|%
        <%= m%>
      <%end%>
    <% end %>
    <div class='container'>
    <%= yield %>
    </div>
    <%# <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name%>
    <%= form.text_field :name, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :login_id %>
    <%= form.text_field :login_id, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<%if @users.count < 1%>
  <h1>No User here, sign up now!</h1>
<%else%>
<h1>Users</h1>
<%if current_user%>
<h2>You are signed in as <%= current_user.name%></h2>
<%end%>

<table class='table table-hover'>
  <thead>
    <tr>
      <th scoh1e='col'>Name</th>
      <th scope='col'>Loginid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.login_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: {confirm: 'You sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<<<<<<< HEAD

<%= link_to 'New User', new_user_path %>

<%end%>
=======
>>>>>>> 86f0f170a681e6a3aa63431215ba5bf25b0c4875

app/views/users/new.html.erb
<div class='com-back'>
<h1>Enter your User and Login id below to Sign Up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class: 'btn text-light bg-success' %>
</div>

app/views/users/show.html.erb
<div class='com-back'>
<%if current_user%>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Login Id:</strong>
  <%= @user.login_id %>
</p>
<%end%>

<%= link_to 'Back', root_path %>

</div>